[appendix]
:appendix-caption: Annex
[[glossary]]
= Glossary

*conformance test class* +
The set of conformance test modules that must be applied to receive a single certificate of
conformance +
{blank}[OGC 08-131r3, definition 4.4]

*feature* +
An abstraction of real world phenomena +
{blank}[ISO 19101-1:2014, definition 4.1.11]

*feature attribute* +
A characteristic of a feature +
{blank}[ISO 19101-1:2014, definition 4.1.12]

[[FeatureType-section]]
*feature type* +
A class of features having common characteristics +
{blank}[ISO 19156:2011, definition 4.7]

*measurement* +
A set of operations having the object of determining the value of a quantity +
{blank}[ISO 19101-2:2018, definition 3.21] / [VIM:1993, 2.1]

*model* +
An abstraction of some aspects of reality +
{blank}[ISO 19109:2015, definition 4.15]

*observation* +
The act of measuring or otherwise determining the value of a property +
{blank}[ISO 19156:2011, definition 4.11]

*observation procedure* +
A method, algorithm or instrument, or system of these, which may be used in making an
observation +
{blank}[ISO 19156:2011, 4.12]

*observation result* +
An estimate of the value of a property determined through a known observation procedure +
{blank}[ISO 19156:2011, 4.14]

*property* +
A facet or attribute of an object referenced by a name. +
{blank}[ISO 19143:2010, definition 4.21]

*requirements class* +
The aggregate of all requirement modules that must all be satisfied to satisfy a conformance
test class +
{blank}[OGC 08-131r3, definition 4.19]

*schema* +
The formal description of a model +
{blank}[ISO 19101-1:2014, definition 4.1.34]

*sensor* +
A type of observation procedure that provides the estimated value of an observed
property at its output +
{blank}[OGC 08-094r1, definition 4.5]

[[standardization-target-definition]]
*Standardization Target* +
An entity to which some requirements of a standard apply +
{blank}[OGC 08-131r3, definition 4.23]

*timeseries* +
A sequence of data values which are ordered in time +
{blank}[OGC 15-043r3]

*universe of discourse* +
View of the real or hypothetical world that includes everything of interest +
{blank}[ISO 19101-1:2014, definition 4.1.38]

*version* +
Particular variation of a spatial object +
{blank}[INSPIRE Glossary]

=== Abbreviated Terms

* 2D {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Two Dimensional
* 3D {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Three Dimensional
* ALKIS {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} German National Standard for Cadastral Information
* ATKIS {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} German National Standard for Topographic and Cartographic Information
* BIM {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Building Information Modeling
* COLLADA {nbsp} Collaborative Design Activity
* GDI-DE {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Spatial Data Infrastructure Germany (Geodateninfrastruktur Deutschland)
* GDI {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} NRW Geodata Infrastructure North-Rhine Westphalia
* GML {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Geography Markup Language
* IAI {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} International Alliance for Interoperability (now buildingSMART International (bSI))
* IETF {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Internet Engineering Task Force
* IFC {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Industry Foundation Classes
* ISO {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} International Organization for Standardisation
* ISO/TC 211 {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} ISO Technical Committee 211
* LOD {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Level of Detail
* MQTT {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}
* OASIS {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Organisation for the Advancement of Structured Information Standards
* OGC {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Open Geospatial Consortium
* SIG 3D {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Special Interest Group 3D of the GDI-DE
* TIC {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Terrain Intersection Curve
* TIN {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Triangulated Irregular Network
* UML {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Unified Modeling Language
* URI {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Uniform Resource Identifier
* W3C {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} World Wide Web Consortium
* X3D {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Open Standards XML-enabled 3D file format of the Web 3D Consortium
* XML {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Extensible Markup Language
* xAL {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} OASIS extensible Address Language
