[[construction-section]]
=== Construction

The Construction module supports representation of key elements of different types of constructions. These key elements include construction surfaces (e.g floor and ceiling), windows and doors, constructive elements (e.g. beams and slabs), installations, and furniture.

The concepts of the Construction module are defined in the OGC CityGML 3.0 Conceptual Model standard. The UML diagram for the Construction module is available under https://docs.ogc.org/is/20-010/20-010.html#construction-uml[^], the Data Dictionary is available under https://docs.ogc.org/is/20-010/20-010.html#toc62[^].

include::requirements/requirements_class_construction.adoc[]

The Construction Conformance Class implements the following Requirements Class from the CityGML 3.0 Conceptual Model Standard:

* Construction: http://www.opengis.net/spec/CityGML-1/3.0/req/req-class-construction

The applicable GML schema is http://schemas.opengis.net/citygml/construction/3.0/construction.xsd[construction.xsd^].

==== Dependencies

The Construction Requirements Class is dependent on the following Requirements Class from this standard:

* The <<core-section,Core>> Requirements Class which is the only mandatory Requirements Class. This class contains foundational elements upon which a CityGML dataset is built. The <<core-section,Core>> Requirements Class also defines XML elements and types reused by other Requirements Classes.

In addition, the Construction Requirements Class is dependent on the following external OGC and ISO standards:

* <<ogc07-036,GML 3.2>> provides most of the geometry types (e.g., Point, LineString, Polygon) used for spatial representations in this standard. Defines Coordinate Reference Systems. Supports the General Feature Model upon which this standard is based.

* <<ogc10-129r1,GML 3.3>> defines compact encodings of geometry types, linear referencing concepts (e.g., linear element, distance along, Linear Referencing Methods), TINs, and encoding rules for association classes.

==== Implementation Decisions

The following decisions have been made regarding implementation of the CityGML 3.0 Construction conformance class in GML.

. All associations allow by default that the referenced features can be provided inline or by reference.

==== Requirements

include::requirements/construction/REQ_Construction_Elements.adoc[]

//==== GML Elements

The CityGML Construction XML elements are listed in the GML schema http://schemas.opengis.net/citygml/construction/3.0/construction.xsd[construction.xsd^].
