[[core-section]]
=== Core

The Core module defines the basic components of the CityGML conceptual model. This includes abstract base classes that define the core properties of more specialized thematic classes defined in other modules as well as concrete classes that are common to other modules, for example basic data types.

The concepts of the Core module are defined in the OGC CityGML 3.0 Conceptual Model standard. The UML diagram for the Core module is available under https://docs.ogc.org/is/20-010/20-010.html#core-uml[^], the Data Dictionary is available under https://docs.ogc.org/is/20-010/20-010.html#toc49[^].

include::requirements/requirements_class_core.adoc[]

The Core Conformance Class implements the following Requirements Class from the CityGML 3.0 Conceptual Model Standard:

* Core: http://www.opengis.net/spec/CityGML-1/3.0/req/req-class-core
//* ADE: http://www.opengis.net/spec/CityGML-1/3.0/req/req-class-ade

The applicable GML schema is http://schemas.opengis.net/citygml/3.0/core.xsd[core.xsd^].

==== Dependencies

The Core Requirements Class is dependent on the following external OGC and ISO standards:

* <<ogc07-036,GML 3.2>> provides most of the geometry types (e.g., Point, LineString, Polygon) used for spatial representations in this standard. Defines Coordinate Reference Systems. Supports the General Feature Model upon which this standard is based.

* <<ogc10-129r1,GML 3.3>> defines compact encodings of geometry types, linear referencing concepts (e.g., linear element, distance along, Linear Referencing Methods), TINs, and encoding rules for association classes.

[[core-section-implementation-decisions]]
==== Implementation Decisions

The following decisions have been made regarding implementation of the CityGML 3.0 Core conformance class in GML.

. The UML class AnyFeature is an instance of the metaclass FeatureType which is defined in ISO 19109. AnyFeature is the generalization of all feature types and acts as superclass of all classes in the CityGML UML model with the stereotype «FeatureType». A comparable concept is defined in ISO 19136 with the XML element gml:AbstractFeature as the most generic feature in GML and its basic feature model gml:AbstractFeatureType from which all feature defined in GML application schemas and, thus, also in the CityGML application schema, are derived. For this reason, the UML class AnyFeature is not encoded as CityGML-specific XML element, but is simply mapped to gml:AbstractFeature.
. The UML class AbstractFeature is the abstract superclass of all feature types within the CityGML Conceptual Model. This class defines amongst others the attributes featureID, identifier, name, and description. These attributes represent properties that are predefined in ISO 19136 (i.e. gml:id, gml:identifier, gml:name, and gml:description) and are inherited by all features defined in GML application schemas. The attributes were added to the UML model to guarantee that they are available in all possible CityGML encodings. In the GML schema, these attributes are suppressed from being encoded, as they are already inherited by all CityGML features.
. The UML class ImplicitGeometry is represented as an object type that defines the attribute objectID. This attribute was added to the UML model to guarantee that it is available in all possible CityGML encodings. This attribute represents the GML property gml:id which all object types automatically inherit in the GML encoding, thus, this attribute is suppressed from being encoded.
. The UML class XALAddress is a placeholder for representing address details according to the OASIS xAL standard. The class is not encoded in the GML schema, but is simply mapped to xAL:Address, the root element for xAL-based address information.
. As described in <<association-classes-section>>, the UML association class CityObjectRelation is modelled as an intermediate class in an Implementation Model before the GML encoding is applied. In this way, a relation between two features A and B can be represented in such a way that feature A provides the element CityObjectRelation inline, whereas the CityObjectRelation references feature B using XLink. This encoding also ensures that the rule on referencing features from alternative aggregations as described in <<linking-rules-4-section>> is observed.
. All associations allow by default that the referenced features can be provided inline or by reference. However, a restriction is defined for the following association, since it represents an alternative aggregation (see rule on referencing features from alternative aggregations in <<linking-rules-4-section>>):
* The reflexive association generalizesTo of the element AbstractCityObject; here, a city object must reference its generalized city object using XLink.
. An exception to the rule that XLinks shall not be used to reference geometries from another top-level feature (Rule 2 in <<linking-rules-1-section>>) is defined for the element ImplicitGeometry. The concept of ImplicitGeometry requires that different top-level features can reference the same geometry and appearance; thus, XLinks from different top-level features to the same geometry and appearance are allowed in this case.
//. CityModelMember: tagged value "gmlAsGroup = true"

==== Requirements

include::requirements/core/REQ_Core_Elements.adoc[]

The CityGML Core XML elements and their corresponding CityGML UML classes are listed in <<core-xml-elements>>. In addition, the CityGML Core XML elements are documented in the GML schema http://schemas.opengis.net/citygml/3.0/core.xsd[core.xsd^] and in this link:XML-schema-documentation/core.xsd.html[XML Schema documentation^].

//[#core-xml-elements,reftext='{table-caption} {counter:table-num}']
[[core-xml-elements]]
.Core XML Elements
[width="100%",cols="10,10",options="header"]
|===
^|XML Schema Element +
 (link:XML-schema-documentation/core.xsd.html[XML Schema documentation^])
^|Conceptual Model +
(https://docs.ogc.org/is/20-010/20-010.html#core-uml[UML model^]; https://docs.ogc.org/is/20-010/20-010.html#toc49[Data Dictionary^])
|AbstractAppearance |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#AbstractAppearance-section[AbstractAppearance^]
|AbstractCityObject |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#AbstractCityObject-section[AbstractCityObject^]
|AbstractDynamizer |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#AbstractDynamizer-section[AbstractDynamizer^]
|AbstractFeature |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#AbstractFeature-section[AbstractFeature^]
|AbstractFeatureWithLifespan |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#AbstractFeatureWithLifespan-section[AbstractFeatureWithLifespan^]
|AbstractLogicalSpace |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#AbstractLogicalSpace-section[AbstractLogicalSpace^]
|AbstractOccupiedSpace |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#AbstractOccupiedSpace-section[AbstractOccupiedSpace^]
|AbstractPhysicalSpace |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#AbstractPhysicalSpace-section[AbstractPhysicalSpace^]
|AbstractPointCloud |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#AbstractPointCloud-section[AbstractPointCloud^]
|AbstractSpace |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#AbstractSpace-section[AbstractSpace^]
|AbstractSpaceBoundary |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#AbstractSpaceBoundary-section[AbstractSpaceBoundary^]
|AbstractThematicSurface |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#AbstractThematicSurface-section[AbstractThematicSurface^]
|AbstractUnoccupiedSpace |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#AbstractUnoccupiedSpace-section[AbstractUnoccupiedSpace^]
|AbstractVersion |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#AbstractVersion-section[AbstractVersion^]
|AbstractVersionTransition |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#AbstractVersionTransition-section[AbstractVersionTransition^]
|Address |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#Address-section[Address^]
|CityModel |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#CityModel-section[CityModel^]
|CityObjectRelation |«ObjectType» https://docs.ogc.org/is/20-010/20-010.html#CityObjectRelation-section[CityObjectRelation^]
|ClosureSurface |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#ClosureSurface-section[ClosureSurface^]
|ImplicitGeometry |«ObjectType» https://docs.ogc.org/is/20-010/20-010.html#ImplicitGeometry-section[ImplicitGeometry^]
|AbstractGenericAttribute |«DataType» https://docs.ogc.org/is/20-010/20-010.html#AbstractGenericAttribute-section[AbstractGenericAttribute^]
|ADEOfAbstractAppearance |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfAbstractAppearance-section[ADEOfAbstractAppearance^]
|ADEOfAbstractCityObject |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfAbstractCityObject-section[ADEOfAbstractCityObject^]
|ADEOfAbstractDynamizer |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfAbstractDynamizer-section[ADEOfAbstractDynamizer^]
|ADEOfAbstractFeature |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfAbstractFeature-section[ADEOfAbstractFeature^]
|ADEOfAbstractFeatureWithLifespan |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfAbstractFeatureWithLifespan-section[ADEOfAbstractFeatureWithLifespan^]
|ADEOfAbstractLogicalSpace |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfAbstractLogicalSpace-section[ADEOfAbstractLogicalSpace^]
|ADEOfAbstractOccupiedSpace |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfAbstractOccupiedSpace-section[ADEOfAbstractOccupiedSpace^]
|ADEOfAbstractPhysicalSpace |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfAbstractPhysicalSpace-section[ADEOfAbstractPhysicalSpace^]
|ADEOfAbstractPointCloud |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfAbstractPointCloud-section[ADEOfAbstractPointCloud^]
|ADEOfAbstractSpace |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfAbstractSpace-section[ADEOfAbstractSpace^]
|ADEOfAbstractSpaceBoundary |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfAbstractSpaceBoundary-section[ADEOfAbstractSpaceBoundary^]
|ADEOfAbstractThematicSurface |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfAbstractThematicSurface-section[ADEOfAbstractThematicSurface^]
|ADEOfAbstractUnoccupiedSpace |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfAbstractUnoccupiedSpace-section[ADEOfAbstractUnoccupiedSpace^]
|ADEOfAbstractVersion |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfAbstractVersion-section[ADEOfAbstractVersion^]
|ADEOfAbstractVersionTransition |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfAbstractVersionTransition-section[ADEOfAbstractVersionTransition^]
|ADEOfAddress |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfAddress-section[ADEOfAddress^]
|ADEOfCityModel |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfCityModel-section[ADEOfCityModel^]
|ADEOfClosureSurface |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfClosureSurface-section[ADEOfClosureSurface^]
|ExternalReference |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ExternalReference-section[ExternalReference^]
|Occupancy |«DataType» https://docs.ogc.org/is/20-010/20-010.html#Occupancy-section[Occupancy^]
|QualifiedArea |«DataType» https://docs.ogc.org/is/20-010/20-010.html#QualifiedArea-section[QualifiedArea^]
|QualifiedVolume |«DataType» https://docs.ogc.org/is/20-010/20-010.html#QualifiedVolume-section[QualifiedVolume^]
|--- (not mapped to XML, see <<core-section-implementation-decisions>>) |«DataType» https://docs.ogc.org/is/20-010/20-010.html#XALAddress-section[XALAddress^]
|===
