[[waterbody-section]]
=== WaterBody

The WaterBody module supports representation of the thematic aspects and 3D geometry of rivers, canals, lakes, and basins. It does, however, not inherit any hydrological or other dynamic aspects of fluid flow.

The concepts of the WaterBody module are defined in the OGC CityGML 3.0 Conceptual Model standard. The UML diagram for the WaterBody module is available under https://docs.ogc.org/is/20-010/20-010.html#waterbody-uml[^], the Data Dictionary is available under https://docs.ogc.org/is/20-010/20-010.html#toc61[^].

include::requirements/requirements_class_waterbody.adoc[]

The WaterBody Conformance Class implements the following Requirements Class from the CityGML 3.0 Conceptual Model Standard:

* WaterBody: http://www.opengis.net/spec/CityGML-1/3.0/req/req-class-waterbody

The applicable GML schema is http://schemas.opengis.net/citygml/waterbody/3.0/waterBody.xsd[waterBody.xsd^].

==== Dependencies

The WaterBody Requirements Class is dependent on the following Requirements Class from this standard:

* The <<core-section,Core>> Requirements Class which is the only mandatory Requirements Class. This class contains foundational elements upon which a CityGML dataset is built. The <<core-section,Core>> Requirements Class also defines XML elements and types reused by other Requirements Classes.

==== Implementation Decisions

The following decisions have been made regarding implementation of the CityGML 3.0 WaterBody conformance class in GML.

. All associations allow by default that the referenced features can be provided inline or by reference.

==== Requirements

include::requirements/waterbody/REQ_WaterBody_Elements.adoc[]

The CityGML WaterBody XML elements and their corresponding CityGML UML classes are listed in <<waterbody-xml-elements>>. In addition, the CityGML WaterBody XML elements are documented in the GML schema http://schemas.opengis.net/citygml/waterbody/3.0/waterBody.xsd[waterBody.xsd^] and in this https://opengeospatial.github.io/CityGML-3.0Encodings/xsd-doc/3.0/waterBody/[XML Schema documentation^].

//[#water-body-xml-elements,reftext='{table-caption} {counter:table-num}']
[[waterbody-xml-elements]]
.WaterBody XML Elements
[width="100%",cols="10,10",options="header"]
|===
^|XML Schema Element +
 (https://opengeospatial.github.io/CityGML-3.0Encodings/xsd-doc/3.0/waterBody/[XML Schema documentation^])
^|Conceptual Model +
(https://docs.ogc.org/is/20-010/20-010.html#waterbody-uml[UML model^]; https://docs.ogc.org/is/20-010/20-010.html#toc61[Data Dictionary^])
|https://opengeospatial.github.io/CityGML-3.0Encodings/xsd-doc/3.0/waterBody/#element_AbstractWaterBoundarySurface[AbstractWaterBoundarySurface^] |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#AbstractWaterBoundarySurface-section[AbstractWaterBoundarySurface^]
|https://opengeospatial.github.io/CityGML-3.0Encodings/xsd-doc/3.0/waterBody/#element_WaterBody[WaterBody^] |«TopLevelFeatureType» https://docs.ogc.org/is/20-010/20-010.html#WaterBody-section[WaterBody^]
|https://opengeospatial.github.io/CityGML-3.0Encodings/xsd-doc/3.0/waterBody/#element_WaterGroundSurface[WaterGroundSurface^] |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#WaterGroundSurface-section[WaterGroundSurface^]
|https://opengeospatial.github.io/CityGML-3.0Encodings/xsd-doc/3.0/waterBody/#element_WaterSurface[WaterSurface^] |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#WaterSurface-section[WaterSurface^]
|https://opengeospatial.github.io/CityGML-3.0Encodings/xsd-doc/3.0/waterBody/#element_ADEOfAbstractWaterBoundarySurface[ADEOfAbstractWaterBoundarySurface^] |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfAbstractWaterBoundarySurface-section[ADEOfAbstractWaterBoundarySurface^]
|https://opengeospatial.github.io/CityGML-3.0Encodings/xsd-doc/3.0/waterBody/#element_ADEOfWaterBody[ADEOfWaterBody^] |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfWaterBody-section[ADEOfWaterBody^]
|https://opengeospatial.github.io/CityGML-3.0Encodings/xsd-doc/3.0/waterBody/#element_ADEOfWaterGroundSurface[ADEOfWaterGroundSurface^] |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfWaterGroundSurface-section[ADEOfWaterGroundSurface^]
|https://opengeospatial.github.io/CityGML-3.0Encodings/xsd-doc/3.0/waterBody/#element_ADEOfWaterSurface[ADEOfWaterSurface^] |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfWaterSurface-section[ADEOfWaterSurface^]
|===

Surface boundaries are constrained by the following requirement:

include::requirements/Waterbody/REQ_Waterbody_Boundaries.adoc[]

<<waterbody-boundaries-table>> lists the surfaces that are allowed as thematic surface boundaries of the space elements defined in the WaterBody module:

[[waterbody-boundaries-table]]
.WaterBody space elements and their allowed thematic surface boundaries
[cols="40,60",options="headers"]
|===
^|*Space element* ^|*Allowed space boundaries*
|_wtr:WaterBody_
a| * _wtr:AbstractWaterBoundarySurface_ and the substitutable elements: +
{nbsp}{nbsp}{nbsp}{nbsp} _wtr:WaterGroundSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _wtr:WaterSurface_
   * _core:ClosureSurface_
   * _gen:GenericThematicSurface_
   * possible surface elements from ADEs
|===
