[[city-object-group-section]]
=== CityObjectGroup

The CityObjectGroup module supports grouping of city objects. Arbitrary city objects may be aggregated in groups according to user-defined criteria. A group may be further classified by application-specific attributes.

The concepts of the CityObjectGroup module are defined in the OGC CityGML 3.0 Conceptual Model standard. The UML diagram for the CityObjectGroup module is available under https://docs.ogc.org/is/20-010/20-010.html#cityobject-uml[^], the Data Dictionary is available under https://docs.ogc.org/is/20-010/20-010.html#toc52[^].

include::requirements/requirements_class_cityobjectgroup.adoc[]

The CityObjectGroup Conformance Class implements the following Requirements Class from the CityGML 3.0 Conceptual Model Standard:

* CityObjectGroup: http://www.opengis.net/spec/CityGML-1/3.0/req/req-class-cityobjectgroup

The applicable GML schema is http://schemas.opengis.net/citygml/cityobjectgroup/3.0/cityObjectGroup.xsd[cityObjectGroup.xsd^].

==== Dependencies

The CityObjectGroup Requirements Class is dependent on the following Requirements Class from this standard:

* The <<core-section,Core>> Requirements Class which is the only mandatory Requirements Class. This class contains foundational elements upon which a CityGML dataset is built. The <<core-section,Core>> Requirements Class also defines XML elements and types reused by other Requirements Classes.

==== Implementation Decisions

The following decisions have been made regarding implementation of the CityGML 3.0 CityObjectGroup conformance class in GML:

. As described in <<association-classes-section>>, the UML association class Role is modelled as an intermediate class in an Implementation Model before the GML encoding is applied. In this way, a relation between a city object group and the features it groups can be represented in such a way that the city object group provides the Role element inline, whereas the Role element references the features that belong to the city object group using XLink. This encoding also ensures that the rule on referencing features from alternative aggregations as described in <<linking-rules-4-section>> is observed.
. All associations allow by default that the referenced features can be provided inline or by reference. However, a restriction is defined for the following association, since it represents an alternative aggregation (see rule on referencing features from alternative aggregations in <<linking-rules-4-section>>):
* The association parent which connects CityObjectGroup with AbstractCityObject; here, a city object group must reference its parent city object using XLink.

==== Requirements

include::requirements/cityobjectgroup/REQ_CityObjectGroup_Elements.adoc[]

The CityGML CityObjectGroup XML elements and their corresponding CityGML UML classes are listed in <<city-object-group-xml-elements>>. In addition, the CityGML CityObjectGroup XML elements are documented in the GML schema http://schemas.opengis.net/citygml/cityobjectgroup/3.0/cityObjectGroup.xsd[cityObjectGroup.xsd^] and in this link:XML-schema-documentation/cityObjectGroup.xsd.html[XML Schema documentation^].

//[#city-object-group-xml-elements,reftext='{table-caption} {counter:table-num}']
[[city-object-group-xml-elements]]
.CityObjectGroup XML Elements
[width="100%",cols="10,10",options="header"]
|===
^|XML Schema Element +
 (link:XML-schema-documentation/cityObjectGroup.xsd.html[XML Schema documentation^])
^|Conceptual Model +
(https://docs.ogc.org/is/20-010/20-010.html#cityobject-uml[UML model^]; https://docs.ogc.org/is/20-010/20-010.html#toc52[Data Dictionary^])
|CityObjectGroup |«TopLevelFeatureType» https://docs.ogc.org/is/20-010/20-010.html#CityObjectGroup-section[CityObjectGroup^]
|Role |«ObjectType» https://docs.ogc.org/is/20-010/20-010.html#Role-section[Role^]
|ADEOfCityObjectGroup |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfCityObjectGroup-section[ADEOfCityObjectGroup^]
|===
