[[dynamizer-section]]
=== Dynamizer

The Dynamizer module supports the injection of timeseries data for individual attributes of CityGML features. Timeseries data can either be retrieved from external Sensor APIs (e.g. OGC SensorThings API, OGC Sensor Observation Services, MQTT, proprietary platforms), external standardized timeseries files (e.g. OGC TimeseriesML or OGC Observations & Measurements), external tabulated files (e.g CSV) or can be represented inline as basic time- value pairs.

The concepts of the Dynamizer module are defined in the OGC CityGML 3.0 Conceptual Model standard. The UML diagram for the Dynamizer module is available under https://docs.ogc.org/is/20-010/20-010.html#dynamizer-uml[^], the Data Dictionary is available under https://docs.ogc.org/is/20-010/20-010.html#toc53[^].

include::requirements/requirements_class_dynamizer.adoc[]

The Dynamizer Conformance Class implements the following Requirements Class from the CityGML 3.0 Conceptual Model Standard:

* Dynamizer: http://www.opengis.net/spec/CityGML-1/3.0/req/req-class-dynamizer

The applicable GML schema is http://schemas.opengis.net/citygml/dynamizer/3.0/dynamizer.xsd[dynamizer.xsd^].

==== Dependencies

The Dynamizer Requirements Class is dependent on the following Requirements Class from this standard:

* The <<core-section,Core>> Requirements Class which is the only mandatory Requirements Class. This class contains foundational elements upon which a CityGML dataset is built. The <<core-section,Core>> Requirements Class also defines XML elements and types reused by other Requirements Classes.

==== Implementation Decisions

The following decisions have been made regarding implementation of the CityGML 3.0 Dynamizer conformance class in GML.

. All associations allow by default that the referenced features can be provided inline or by reference. However, a restriction is defined for the following association, since it represents an alternative aggregation (see rule on referencing features from alternative aggregations in <<linking-rules-4-section>>):
* The association sensorLocation which connects SensorConnection with AbstractCityObject; here, a sensor connection must reference the city object for which it provides sensor information using XLink.

==== Requirements

include::requirements/dynamizer/REQ_Dynamizer_Elements.adoc[]

The CityGML Dynamizer XML elements and their corresponding CityGML UML classes are listed in <<dynamizer-xml-elements>>. In addition, the CityGML Dynamizer XML elements are documented in the GML schema http://schemas.opengis.net/citygml/dynamizer/3.0/dynamizer.xsd[dynamizer.xsd^] and in this link:XML-schema-documentation/dynamizer.xsd.html[XML Schema documentation^].

//[#dynamizer-xml-elements,reftext='{table-caption} {counter:table-num}']
[[dynamizer-xml-elements]]
.Dynamizer XML Elements
[width="100%",cols="10,10",options="header"]
|===
^|XML Schema Element +
 (link:XML-schema-documentation/dynamizer.xsd.html[XML Schema documentation^])
^|Conceptual Model +
(https://docs.ogc.org/is/20-010/20-010.html#dynamizer-uml[UML model^]; https://docs.ogc.org/is/20-010/20-010.html#toc53[Data Dictionary^])
|AbstractAtomicTimeseries |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#AbstractAtomicTimeseries-section[AbstractAtomicTimeseries^]
|AbstractTimeseries |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#AbstractTimeseries-section[AbstractTimeseries^]
|CompositeTimeseries |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#CompositeTimeseries-section[CompositeTimeseries^]
|Dynamizer |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#Dynamizer-section[Dynamizer^]
|GenericTimeseries |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#GenericTimeseries-section[GenericTimeseries^]
|StandardFileTimeseries |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#StandardFileTimeseries-section[StandardFileTimeseries^]
|TabulatedFileTimeseries |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#TabulatedFileTimeseries-section[TabulatedFileTimeseries^]
|ADEOfAbstractAtomicTimeseries |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfAbstractAtomicTimeseries-section[ADEOfAbstractAtomicTimeseries^]
|ADEOfAbstractTimeseries |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfAbstractTimeseries-section[ADEOfAbstractTimeseries^]
|ADEOfCompositeTimeseries |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfCompositeTimeseries-section[ADEOfCompositeTimeseries^]
|ADEOfDynamizer |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfDynamizer-section[ADEOfDynamizer^]
|ADEOfGenericTimeseries |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfGenericTimeseries-section[ADEOfGenericTimeseries^]
|ADEOfStandardFileTimeseries |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfStandardFileTimeseries-section[ADEOfStandardFileTimeseries^]
|ADEOfTabulatedFileTimeseries |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfTabulatedFileTimeseries-section[ADEOfTabulatedFileTimeseries^]
|SensorConnection |«DataType» https://docs.ogc.org/is/20-010/20-010.html#SensorConnection-section[SensorConnection^]
|TimeseriesComponent |«DataType» https://docs.ogc.org/is/20-010/20-010.html#TimeseriesComponent-section[TimeseriesComponent^]
|TimeValuePair |«DataType» https://docs.ogc.org/is/20-010/20-010.html#TimeValuePair-section[TimeValuePair^]
|===
