[[point-cloud-section]]
=== PointCloud

The PointCloud module supports representation of CityGML features by a collection of points.

The concepts of the PointCloud module are defined in the OGC CityGML 3.0 Conceptual Model standard. The UML diagram for the PointCloud module is available under https://docs.ogc.org/is/20-010/20-010.html#pointcloud-uml[^], the Data Dictionary is available under https://docs.ogc.org/is/20-010/20-010.html#toc56[^].

include::requirements/requirements_class_pointcloud.adoc[]

The PointCloud Conformance Class implements the following Requirements Class from the CityGML 3.0 Conceptual Model Standard:

* PointCloud: http://www.opengis.net/spec/CityGML-1/3.0/req/req-class-pointcloud

The applicable GML schema is http://schemas.opengis.net/citygml/pointcloud/3.0/pointCloud.xsd[pointCloud.xsd^].

==== Dependencies

The PointCloud Requirements Class is dependent on the following Requirements Class from this standard:

* The <<core-section,Core>> Requirements Class which is the only mandatory Requirements Class. This class contains foundational elements upon which a CityGML dataset is built. The <<core-section,Core>> Requirements Class also defines XML elements and types reused by other Requirements Classes.

==== Implementation Decisions

The following decisions have been made regarding implementation of the CityGML 3.0 PointCloud conformance class in GML.

. All associations allow by default that the referenced features can be provided inline or by reference.
. The PointCloud module allows for representing the geometries of city objects by 3D point clouds in three ways. Examples for each representation option are provided in <<annex-examples-pointcloud>>:
* A MultiPoint geometry is provided inline with the CityGML file, i.e., the point cloud of a specific feature is embedded directly within the feature represented by the point cloud.
* A separate point cloud file is provided for every feature. Each feature in the CityGML file references the corresponding point cloud file.
* One point cloud file is provided that contains all points from all features in a specific area. In the point cloud file, all points belonging to a specific feature have the same value set in the attribute “point_source_id”. Each feature in the CityGML instance document references the point cloud file and all points with the corresponding value in the attribute “point_source_id”.

==== Requirements

include::requirements/pointcloud/REQ_PointCloud_Elements.adoc[]

The CityGML PointCloud XML elements and their corresponding CityGML UML classes are listed in <<point-cloud-xml-elements>>. In addition, the CityGML PointCloud XML elements are documented in the GML schema http://schemas.opengis.net/citygml/pointcloud/3.0/pointCloud.xsd[pointCloud.xsd^] and in this https://opengeospatial.github.io/CityGML-3.0Encodings/xsd-doc/3.0/pointCloud/[XML Schema documentation^].

//[#point-cloud-xml-elements,reftext='{table-caption} {counter:table-num}']
[[point-cloud-xml-elements]]
.PointCloud XML Elements
[width="100%",cols="10,10",options="header"]
|===
^|XML Schema Element +
 (https://opengeospatial.github.io/CityGML-3.0Encodings/xsd-doc/3.0/pointCloud/[XML Schema documentation^])
^|Conceptual Model +
(https://docs.ogc.org/is/20-010/20-010.html#pointcloud-uml[UML model^]; https://docs.ogc.org/is/20-010/20-010.html#toc56[Data Dictionary^])
|https://opengeospatial.github.io/CityGML-3.0Encodings/xsd-doc/3.0/pointCloud/#element_PointCloud[PointCloud^] |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#PointCloud-section[PointCloud^]
|https://opengeospatial.github.io/CityGML-3.0Encodings/xsd-doc/3.0/pointCloud/#element_ADEOfPointCloud[ADEOfPointCloud^] |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfPointCloud-section[ADEOfPointCloud^]
|===
