[[bridge-section]]
=== Bridge

The Bridge module supports representation of thematic and spatial aspects of bridges, bridge parts, bridge installations, and interior bridge structures.

The concepts of the Bridge module are defined in the OGC CityGML 3.0 Conceptual Model standard. The UML diagram for the Bridge module is available under https://docs.ogc.org/is/20-010/20-010.html#bridge-uml[^], the Data Dictionary is available under https://docs.ogc.org/is/20-010/20-010.html#toc63[^].

include::requirements/requirements_class_bridge.adoc[]

The Bridge Conformance Class implements the following Requirements Class from the CityGML 3.0 Conceptual Model Standard:

* Bridge: http://www.opengis.net/spec/CityGML-1/3.0/req/req-class-bridge

The applicable GML schema is http://schemas.opengis.net/citygml/bridge/3.0/bridge.xsd[bridge.xsd^].

==== Dependencies

The Bridge Requirements Class is dependent on the following Requirements Class from this standard:

* The <<core-section,Core>> Requirements Class which is the only mandatory Requirements Class. This class contains foundational elements upon which a CityGML dataset is built. The <<core-section,Core>> Requirements Class also defines XML elements and types reused by other Requirements Classes.

==== Implementation Decisions

The following decisions have been made regarding implementation of the CityGML 3.0 Bridge conformance class in GML:

. All associations allow by default that the referenced features can be provided inline or by reference.

==== Requirements

include::requirements/bridge/REQ_Bridge_Elements.adoc[]

The CityGML Bridge XML elements and their corresponding CityGML UML classes are listed in <<bridge-xml-elements>>. In addition, the CityGML Bridge XML elements are documented in the GML schema http://schemas.opengis.net/citygml/bridge/3.0/bridge.xsd[bridge.xsd^] and in this link:XML-schema-documentation/bridge.xsd.html[XML Schema documentation^].

//[#bridge-xml-elements,reftext='{table-caption} {counter:table-num}']
[[bridge-xml-elements]]
.Bridge XML Elements
[width="100%",cols="10,10",options="header"]
|===
^|XML Schema Element +
 (link:XML-schema-documentation/bridge.xsd.html[XML Schema documentation^])
^|Conceptual Model +
(https://docs.ogc.org/is/20-010/20-010.html#bridge-uml[UML model^]; https://docs.ogc.org/is/20-010/20-010.html#toc63[Data Dictionary^])
| AbstractBridge |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#AbstractBridge-section[AbstractBridge^]
| Bridge |«TopLevelFeatureType» https://docs.ogc.org/is/20-010/20-010.html#Bridge-section[Bridge^]
| BridgeConstructiveElement |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#BridgeConstructiveElement-section[BridgeConstructiveElement^]
| BridgeFurniture |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#BridgeFurniture-section[BridgeFurniture^]
| BridgeInstallation |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#BridgeInstallation-section[BridgeInstallation^]
| BridgePart |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#BridgePart-section[BridgePart^]
| BridgeRoom |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#BridgeRoom-section[BridgeRoom^]
| ADEOfAbstractBridge |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfAbstractBridge-section[ADEOfAbstractBridge^]
| ADEOfBridge |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfBridge-section[ADEOfBridge^]
| ADEOfBridgeConstructiveElement |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfBridgeConstructiveElement-section[ADEOfBridgeConstructiveElement^]
| ADEOfBridgeFurniture |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfBridgeFurniture-section[ADEOfBridgeFurniture^]
| ADEOfBridgeInstallation |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfBridgeInstallation-section[ADEOfBridgeInstallation^]
| ADEOfBridgePart |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfBridgePart-section[ADEOfBridgePart^]
| ADEOfBridgeRoom |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfBridgeRoom-section[ADEOfBridgeRoom^]
|===
