[[water-body-section]]
=== Water Body Conformance Class

The WaterBody module supports representation of the thematic aspects and 3D geometry of rivers, canals, lakes, and basins. It does, however, not inherit any hydrological or other dynamic aspects of fluid flow.

include::requirements/requirements_class_waterbody.adoc[]

The Water Body Conformance Class implements the following Requirements Class from the CityGML 3.0 Conceptual Model Standard:

* WaterBody: http://www.opengis.net/spec/CityGML-1/3.0/req/req-class-waterbody

The applicable GML schema is http://schemas.opengis.net/citygml/3.0/waterBody.xsd[waterBody.xsd].

==== Dependencies

The Appearance Requirements Class is dependent on the following Requirements Class from this standard:

* The <<core-section,Core>> Requirements Class which is the only mandatory Requirements Class. This class contains foundational elements upon which a CityGML dataset is built. The <<core-section,Core>> Requirements Class also defines XML elements and types reused by other Requirements Classes.

In addition, the Appearance Requirements Class is dependent on the following external OGC and ISO standards:

* <<ogc07-036,GML 3.2>> provides most of the geometry types (e.g., Point, LineString, Polygon) used for spatial representations in this standard. Defines Coordinate Reference Systems. Supports the General Feature Model upon which this standard is based.

* <<ogc10-129r1,GML 3.3>> defines compact encodings of geometry types, linear referencing concepts (e.g., linear element, distance along, Linear Referencing Methods), TINs, and encoding rules for association classes.

==== Implementation Decisions

The following decisions have been made regarding implementation of the CityGML 3.0 Water Body conformance class in GML.

. All associations allow by default that the referenced features can be provided inline or by reference.

==== Requirements

include::requirements/waterbody/REQ_WaterBody_Elements.adoc[]

//==== GML Elements

The CityGML Water Body XML elements are listed in the GML schema http://schemas.opengis.net/citygml/3.0/waterBody.xsd[waterBody.xsd].
