[[point-cloud-section]]
=== PointCloud

The PointCloud module supports representation of CityGML features by a collection of points.

The concepts of the PointCloud module are defined in the OGC CityGML 3.0 Conceptual Model standard. The UML diagram for the PointCloud module is available under https://docs.ogc.org/is/20-010/20-010.html#pointcloud-uml[^], the Data Dictionary is available under https://docs.ogc.org/is/20-010/20-010.html#toc56[^].

include::requirements/requirements_class_pointcloud.adoc[]

The PointCloud Conformance Class implements the following Requirements Class from the CityGML 3.0 Conceptual Model Standard:

* PointCloud: http://www.opengis.net/spec/CityGML-1/3.0/req/req-class-pointcloud

The applicable GML schema is http://schemas.opengis.net/citygml/pointcloud/3.0/pointCloud.xsd[pointCloud.xsd^].

==== Dependencies

The PointCloud Requirements Class is dependent on the following Requirements Class from this standard:

* The <<core-section,Core>> Requirements Class which is the only mandatory Requirements Class. This class contains foundational elements upon which a CityGML dataset is built. The <<core-section,Core>> Requirements Class also defines XML elements and types reused by other Requirements Classes.

In addition, the PointCloud Requirements Class is dependent on the following external OGC and ISO standards:

* <<ogc07-036,GML 3.2>> provides most of the geometry types (e.g., Point, LineString, Polygon) used for spatial representations in this standard. Defines Coordinate Reference Systems. Supports the General Feature Model upon which this standard is based.

* <<ogc10-129r1,GML 3.3>> defines compact encodings of geometry types, linear referencing concepts (e.g., linear element, distance along, Linear Referencing Methods), TINs, and encoding rules for association classes.

==== Implementation Decisions

The following decisions have been made regarding implementation of the CityGML 3.0 PointCloud conformance class in GML.

. All associations allow by default that the referenced features can be provided inline or by reference.
. The PointCloud module allows for representing the geometries of city objects by 3D point clouds in three ways. Examples for each representation option are provided in <<annex-examples-pointcloud>>:
* A MultiPoint geometry is provided inline with the CityGML file, i.e. the point cloud of a specific feature is embedded directly within the feature represented by the point cloud.
* A separate point cloud file is provided for every feature. Each feature in the CityGML file references the corresponding point cloud file.
* One point cloud file is provided that contains all points from all features in a specific area. In the point cloud file, all points belonging to a specific feature have the same value set in the attribute “point_source_id”. Each feature in the CityGML instance document references the point cloud file and all points with the corresponding value in the attribute “point_source_id”.

==== Requirements

include::requirements/pointcloud/REQ_PointCloud_Elements.adoc[]

//==== GML Elements

The CityGML PointCloud XML elements are listed in the GML schema http://schemas.opengis.net/citygml/pointcloud/3.0/pointCloud.xsd[pointCloud.xsd^].
