[[land-use-section]]
=== LandUse

The LandUse module supports representation of areas of the earth’s surface dedicated to a specific land use.

The concepts of the LandUse module are defined in the OGC CityGML 3.0 Conceptual Model standard. The UML diagram for the LandUse module is available under https://docs.ogc.org/is/20-010/20-010.html#landuse-uml[^], the Data Dictionary is available under https://docs.ogc.org/is/20-010/20-010.html#toc55[^].

include::requirements/requirements_class_landuse.adoc[]

The LandUse Conformance Class implements the following Requirements Class from the CityGML 3.0 Conceptual Model Standard:

* LandUse: http://www.opengis.net/spec/CityGML-1/3.0/req/req-class-landuse

The applicable GML schema is http://schemas.opengis.net/citygml/landuse/3.0/landUse.xsd[landUse.xsd^].

==== Dependencies

The LandUse Requirements Class is dependent on the following Requirements Class from this standard:

* The <<core-section,Core>> Requirements Class which is the only mandatory Requirements Class. This class contains foundational elements upon which a CityGML dataset is built. The <<core-section,Core>> Requirements Class also defines XML elements and types reused by other Requirements Classes.

==== Implementation Decisions

The following decisions have been made regarding implementation of the CityGML 3.0 LandUse conformance class in GML.

. All associations allow by default that the referenced features can be provided inline or by reference.

==== Requirements

include::requirements/landuse/REQ_LandUse_Elements.adoc[]

The CityGML LandUse XML elements and their corresponding CityGML UML classes are listed in <<land-use-xml-elements>>. In addition, the CityGML LandUse XML elements are documented in the GML schema http://schemas.opengis.net/citygml/landuse/3.0/landUse.xsd[landUse.xsd^] and in this link:XML-schema-documentation/landUse.xsd.html[XML Schema documentation^].

//[#land-use-xml-elements,reftext='{table-caption} {counter:table-num}']
[[land-use-xml-elements]]
.LandUse XML Elements
[width="100%",cols="10,10",options="header"]
|===
^|XML Schema Element +
 (link:XML-schema-documentation/landUse.xsd.html[XML Schema documentation^])
^|Conceptual Model +
(https://docs.ogc.org/is/20-010/20-010.html#landuse-uml[UML model^]; https://docs.ogc.org/is/20-010/20-010.html#toc55[Data Dictionary^])
|LandUse |«TopLevelFeatureType» https://docs.ogc.org/is/20-010/20-010.html#LandUse-section[LandUse^]
|ADEOfLandUse |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfLandUse-section[ADEOfLandUse^]
|===
