[[dynamizer-section]]
=== Dynamizer Conformance Class

The Dynamizer Conformance Class implements the following Requirements Class from the CityGML 3.0 Conceptual Model Standard:

* Dynamizer: http://www.opengis.net/spec/CityGML-1/3.0/req/req-class-dynamizer

The applicable GML schema is http://schemas.opengis.net/citygml/3.0/dynamizer.xsd[dynamizer.xsd].

include::requirements/requirements_class_dynamizer.adoc[]

==== GML Elements

The CityGML Dynamizer XML elements are listed in the GML schema http://schemas.opengis.net/citygml/3.0/dynamizer.xsd[dynamizer.xsd].

==== Implementation Decisions

The following decisions have been made regarding implementation of the CityGML 3.0 Dynamizer conformance class in GML.

. All associations allow by default that the referenced features can be provided inline or by reference. However, a restriction is defined for the following association, since it represents an alternative aggregation (see rule on referencing features from alternative aggregations in <<linking-rules-4-section>>):
* The association sensorLocation which connects SensorConnection with AbstractCityObject; here, a sensor connection must reference the city object for which it provides sensor information using XLink.

==== Requirements

include::requirements/dynamizer/REQ_Dynamizer_Elements.adoc[]
