[[city-object-group-section]]
=== City Object Group Conformance Class

The CityObjectGroup module supports grouping of city objects. Arbitrary city objects may be aggregated in groups according to user-defined criteria. A group may be further classified by application-specific attributes.

include::requirements/requirements_class_cityobjectgroup.adoc[]

The City Object Group Conformance Class implements the following Requirements Class from the CityGML 3.0 Conceptual Model Standard:

* CityObjectGroup: http://www.opengis.net/spec/CityGML-1/3.0/req/req-class-cityobjectgroup

The applicable GML schema is http://schemas.opengis.net/citygml/3.0/cityObjectGroup.xsd[cityObjectGroup.xsd].

==== Dependencies

The Appearance Requirements Class is dependent on the following Requirements Class from this standard:

* The <<core-section,Core>> Requirements Class which is the only mandatory Requirements Class. This class contains foundational elements upon which a CityGML dataset is built. The <<core-section,Core>> Requirements Class also defines XML elements and types reused by other Requirements Classes.

In addition, the Appearance Requirements Class is dependent on the following external OGC and ISO standards:

* <<ogc07-036,GML 3.2>> provides most of the geometry types (e.g., Point, LineString, Polygon) used for spatial representations in this standard. Defines Coordinate Reference Systems. Supports the General Feature Model upon which this standard is based.

* <<ogc10-129r1,GML 3.3>> defines compact encodings of geometry types, linear referencing concepts (e.g., linear element, distance along, Linear Referencing Methods), TINs, and encoding rules for association classes.

==== Implementation Decisions

The following decisions have been made regarding implementation of the CityGML 3.0 City Object Group conformance class in GML.

. As described in <<association-classes-section>>, the UML association class Role is modelled as an intermediate class in an Implementation Model before the GML encoding is applied. In this way, a relation between a city object group and the features it groups can be represented in such a way that the city object group provides the element Role inline, whereas the Role references the features that belong to the city object group using XLink. This encoding also ensures that the rule on referencing features from alternative aggregations as described in <<linking-rules-4-section>> is observed.
. All associations allow by default that the referenced features can be provided inline or by reference. However, a restriction is defined for the following association, since it represents an alternative aggregation (see rule on referencing features from alternative aggregations in <<linking-rules-4-section>>):
* The association parent which connects CityObjectGroup with AbstractCityObject; here, a city object group must reference its parent city object using XLink.

==== Requirements

include::requirements/cityobjectgroup/REQ_CityObjectGroup_Elements.adoc[]

//==== GML Elements

The CityGML City Object Group XML elements are listed in the GML schema http://schemas.opengis.net/citygml/3.0/cityObjectGroup.xsd[cityObjectGroup.xsd].
