[[transportation-section]]
=== Transportation

The Transportation module supports representation of the transportation infrastructure. Transportation features include roads, tracks, waterways, railways, and squares. Transportation features may be represented as a network and/or as a collection of spaces or surface elements embedded in a three-dimensional space.

The concepts of the Transportation module are defined in the OGC CityGML 3.0 Conceptual Model standard. The UML diagram for the Transportation module is available under https://docs.ogc.org/is/20-010/20-010.html#transportation-uml[^], the Data Dictionary is available under https://docs.ogc.org/is/20-010/20-010.html#toc58[^].

include::requirements/requirements_class_transportation.adoc[]

The Transportation Conformance Class implements the following Requirements Class from the CityGML 3.0 Conceptual Model Standard:

* Transportation: http://www.opengis.net/spec/CityGML-1/3.0/req/req-class-transportation

The applicable GML schema is http://schemas.opengis.net/citygml/transportation/3.0/transportation.xsd[transportation.xsd^].

==== Dependencies

The Transportation Requirements Class is dependent on the following Requirements Class from this standard:

* The <<core-section,Core>> Requirements Class which is the only mandatory Requirements Class. This class contains foundational elements upon which a CityGML dataset is built. The <<core-section,Core>> Requirements Class also defines XML elements and types reused by other Requirements Classes.

In addition, the Transportation Requirements Class is dependent on the following external OGC and ISO standards:

* <<ogc07-036,GML 3.2>> provides most of the geometry types (e.g., Point, LineString, Polygon) used for spatial representations in this standard. Defines Coordinate Reference Systems. Supports the General Feature Model upon which this standard is based.

* <<ogc10-129r1,GML 3.3>> defines compact encodings of geometry types, linear referencing concepts (e.g., linear element, distance along, Linear Referencing Methods), TINs, and encoding rules for association classes.

==== Implementation Decisions

The following decisions have been made regarding implementation of the CityGML 3.0 Transportation conformance class in GML.

. All associations allow by default that the referenced features can be provided inline or by reference. However, restrictions are defined for the following associations, since they represent alternative aggregations (see rule on referencing features from alternative aggregations in <<linking-rules-4-section>>):
* The reflexive association successor of TrafficSpace; here, a traffic space must reference its succeeding traffic space using XLink.
* The reflexive association predecessor of TrafficSpace; here, a traffic space must reference its preceding traffic space using XLink.

==== Requirements

include::requirements/transportation/REQ_Transportation_Elements.adoc[]

//==== GML Elements

The CityGML Transportation XML elements are listed in the GML schema http://schemas.opengis.net/citygml/transportation/3.0/transportation.xsd[transportation.xsd^].
