[[versioning-section]]
=== Versioning Conformance Class

The Versioning Conformance Class implements the following Requirements Class from the CityGML 3.0 Conceptual Model Standard:

* Versioning: http://www.opengis.net/spec/CityGML-1/3.0/req/req-class-versioning

The applicable GML schema is http://schemas.opengis.net/citygml/3.0/versioning.xsd[versioning.xsd].

include::requirements/requirements_class_versioning.adoc[]

==== GML Elements

The CityGML Versioning XML elements are listed in the GML schema http://schemas.opengis.net/citygml/3.0/versioning.xsd[versioning.xsd].

==== Implementation Decisions

The following decisions have been made regarding implementation of the CityGML 3.0 Versioning conformance class in GML.

. All associations allow by default that the referenced features can be provided inline or by reference. However, restrictions are defined for the following associations, since they represent alternative aggregations (see rule on referencing features from alternative aggregations in <<linking-rules-4-section>>):
* The association oldFeature which connects Transaction with AbstractFeatureWithLifespan; here, a transaction must reference the version of the city object prior to the transaction using XLink.
* The association newFeature which connects Transaction with AbstractFeatureWithLifespan; here, a transaction must reference the version of the city object subsequent to the transaction using XLink.
* The association from which connects VersionTransition with Version; here, a version transition must reference the predecessor version of the VersionTransition using XLink.
* The association to which connects VersionTransition with Version; here, a version transition must reference the successor version of the VersionTransition using XLink.
* The association versionMember which connects Version with AbstractFeatureWithLifespan; here, a version must reference the features that are part of this version using XLink.

==== Requirements

include::requirements/versioning/REQ_Versioning_Elements.adoc[]
