[[transportation-section]]
=== Transportation Conformance Class

The Transportation Conformance Class implements the following Requirements Class from the CityGML 3.0 Conceptual Model Standard:

* Transportation: http://www.opengis.net/spec/CityGML-1/3.0/req/req-class-transportation

The applicable GML schema is http://schemas.opengis.net/citygml/3.0/transportation.xsd[transportation.xsd].

include::requirements/requirements_class_transportation.adoc[]

==== GML Elements

The CityGML Transportation XML elements are listed in the GML schema http://schemas.opengis.net/citygml/3.0/transportation.xsd[transportation.xsd].

==== Implementation Decisions

The following decisions have been made regarding implementation of the CityGML 3.0 Transportation conformance class in GML.

. All associations allow by default that the referenced features can be provided inline or by reference. However, restrictions are defined for the following associations, since they represent alternative aggregations (see rule on referencing features from alternative aggregations in <<linking-rules-4-section>>):
* The reflexive association successor of TrafficSpace; here, a traffic space must reference its succeeding traffic space using XLink.
* The reflexive association predecessor of TrafficSpace; here, a traffic space must reference its preceding traffic space using XLink.

==== Requirements

include::requirements/transportation/REQ_Transportation_Elements.adoc[]
