[[appearance-section]]
=== Appearance Conformance Class

NOTE: replace with appropriate text

Features of the land, such as naturally occurring water features and vegetation are specified in the LandFeature Requirements Class as land features. Also included are models of the land surface and subsurface layers. Improvements to the land such as the construction of an embankment or the planting of landscape material are considered to be part of Site Facilities in the Facility Requirements Class.

The Appearance Conformance Class implements the following Requirements Classes from the CityGML 3.0 Conceptual Model Standard:

* Appearance: http://www.opengis.net/spec/CityGML-1/3.0/req/req-class-appearance

The applicable GML schema is http://schemas.opengis.net/citygml/3.0/appearance.xsd[appearance.xsd]

include::requirements/requirements_class_appearance.adoc[]

==== Dependencies

The Appearance Requirements Classes is dependent on the following Requirements Classes from this standard.

* The <<core-section,Core>> Requirements Class is the only mandatory Requirements Class. This class contains foundational elements upon which a CityGML dataset is built. The <<core-section,Core>> Requirements Class also defines XML elements and types reused by other Requirements Classes.

* <<ogc07-036,GML 3.2>> provides most of the geometry types (e.g., Point, LineString, Polygon) used for spatial representations in this Standard. Defines Coordinate Reference Systems. Supports the General Feature Model upon which this Standard is based.

* <<ogc10-129r1,GML 3.3>> defines the linear referencing concepts (e.g., linear element, distance along, Linear Referencing Methods) used for linearly referenced locations in this Standard. Also included are TINs.

==== GML Elements

The CityGML Appearance XML elements and their corresponding CityGML UML classes are shown in <<appearance-xml-elements>>.

[#appearance-xml-elements,reftext='{table-caption} {counter:table-num}']
.Appearance XML Elements
[width="100%",cols="10,10",options="header"]
|===
^|XML Schema Element  ^|Conceptual Model
|AbstractSurfaceData | «FeatureType» <<AbstractSurfaceData-section,AbstractSurfaceData>>
|AbstractTexture |«FeatureType» <<AbstractTexture-section,AbstractTexture>>
|Appearance |«FeatureType» <<Appearance-section,Appearance>>
|GeoreferencedTexture |«FeatureType» <<GeoreferencedTexture-section,GeoreferencedTexture>>
|ParameterizedTexture |«FeatureType» <<ParameterizedTexture-section,ParameterizedTexture>>
|TextureAssociation |«ObjectType» <<TextureAssociation-section,TextureAssociation>>
|X3DMaterial |«FeatureType» <<X3DMaterial-section,X3DMaterial>>
|AbstractTextureParameterization |«DataType» <<AbstractTextureParameterization-section,AbstractTextureParameterization>>
|ADEOfAbstractSurfaceData |«DataType» <<ADEOfAbstractSurfaceData-section,ADEOfAbstractSurfaceData>>
|ADEOfAbstractTexture |«DataType» <<ADEOfAbstractTexture-section,ADEOfAbstractTexture>>
|ADEOfAppearance |«DataType» <<ADEOfAppearance-section,ADEOfAppearance>>
|ADEOfGeoreferencedTexture |«DataType» <<ADEOfGeoreferencedTexture-section,ADEOfGeoreferencedTexture>>
|ADEOfParameterizedTexture |«DataType» <<ADEOfParameterizedTexture-section,ADEOfParameterizedTexture>>
|ADEOfX3DMaterial |«DataType» <<ADEOfX3DMaterial-section,ADEOfX3DMaterial>>
|TexCoordGen |«DataType» <<TexCoordGen-section,TexCoordGen>>
|TexCoordList |«DataType» <<TexCoordList-section,TexCoordList>>
|===

==== Implementation Decisions

The following decisions have been made regarding implementation of the CityGML 3.0 `Appearance` conformance class in GML.

. decision 1
. decision 2

==== Requirements

include::requirements/appearance/REQ_Appearance_Elements.adoc[]
