[[tunnel-section]]
=== Tunnel

The Tunnel module supports representation of thematic and spatial aspects of tunnels, tunnel parts, tunnel installations, and interior tunnel structures.

The concepts of the Tunnel module are defined in the OGC CityGML 3.0 Conceptual Model standard. The UML diagram for the Tunnel module is available under https://docs.ogc.org/is/20-010/20-010.html#tunnel-uml[^], the Data Dictionary is available under https://docs.ogc.org/is/20-010/20-010.html#toc65[^].

include::requirements/requirements_class_tunnel.adoc[]

The Tunnel Conformance Class implements the following Requirements Class from the CityGML 3.0 Conceptual Model Standard:

* Tunnel: http://www.opengis.net/spec/CityGML-1/3.0/req/req-class-tunnel

The applicable GML schema is http://schemas.opengis.net/citygml/tunnel/3.0/tunnel.xsd[tunnel.xsd^].

==== Dependencies

The Tunnel Requirements Class is dependent on the following Requirements Class from this standard:

* The <<core-section,Core>> Requirements Class which is the only mandatory Requirements Class. This class contains foundational elements upon which a CityGML dataset is built. The <<core-section,Core>> Requirements Class also defines XML elements and types reused by other Requirements Classes.

==== Implementation Decisions

The following decisions have been made regarding implementation of the CityGML 3.0 Tunnel conformance class in GML.

. All associations allow by default that the referenced features can be provided inline or by reference.

==== Requirements

include::requirements/tunnel/REQ_Tunnel_Elements.adoc[]

The CityGML Tunnel XML elements and their corresponding CityGML UML classes are listed in <<tunnel-xml-elements>>. In addition, the CityGML Tunnel XML elements are documented in the GML schema http://schemas.opengis.net/citygml/tunnel/3.0/tunnel.xsd[tunnel.xsd^] and in this https://opengeospatial.github.io/CityGML-3.0Encodings/xsd-doc/3.0/tunnel/[XML Schema documentation^].

//[#tunnel-xml-elements,reftext='{table-caption} {counter:table-num}']
[[tunnel-xml-elements]]
.Tunnel XML Elements
[width="100%",cols="10,10",options="header"]
|===
^|XML Schema Element +
 (https://opengeospatial.github.io/CityGML-3.0Encodings/xsd-doc/3.0/tunnel/[XML Schema documentation^])
^|Conceptual Model +
(https://docs.ogc.org/is/20-010/20-010.html#tunnel-uml[UML model^]; https://docs.ogc.org/is/20-010/20-010.html#toc65[Data Dictionary^])
|https://opengeospatial.github.io/CityGML-3.0Encodings/xsd-doc/3.0/tunnel/#element_AbstractTunnel[AbstractTunnel^] |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#AbstractTunnel-section[AbstractTunnel^]
|https://opengeospatial.github.io/CityGML-3.0Encodings/xsd-doc/3.0/tunnel/#element_HollowSpace[HollowSpace^] |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#HollowSpace-section[HollowSpace^]
|https://opengeospatial.github.io/CityGML-3.0Encodings/xsd-doc/3.0/tunnel/#element_Tunnel[Tunnel^] |«TopLevelFeatureType» https://docs.ogc.org/is/20-010/20-010.html#Tunnel-section[Tunnel^]
|https://opengeospatial.github.io/CityGML-3.0Encodings/xsd-doc/3.0/tunnel/#element_TunnelConstructiveElement[TunnelConstructiveElement^] |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#TunnelConstructiveElement-section[TunnelConstructiveElement^]
|https://opengeospatial.github.io/CityGML-3.0Encodings/xsd-doc/3.0/tunnel/#element_TunnelFurniture[TunnelFurniture^] |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#TunnelFurniture-section[TunnelFurniture^]
|https://opengeospatial.github.io/CityGML-3.0Encodings/xsd-doc/3.0/tunnel/#element_TunnelInstallation[TunnelInstallation^] |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#TunnelInstallation-section[TunnelInstallation^]
|https://opengeospatial.github.io/CityGML-3.0Encodings/xsd-doc/3.0/tunnel/#element_TunnelPart[TunnelPart^] |«FeatureType» https://docs.ogc.org/is/20-010/20-010.html#TunnelPart-section[TunnelPart^]
|https://opengeospatial.github.io/CityGML-3.0Encodings/xsd-doc/3.0/tunnel/#element_ADEOfAbstractTunnel[ADEOfAbstractTunnel^] |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfAbstractTunnel-section[ADEOfAbstractTunnel^]
|https://opengeospatial.github.io/CityGML-3.0Encodings/xsd-doc/3.0/tunnel/#element_ADEOfHollowSpace[ADEOfHollowSpace^] |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfHollowSpace-section[ADEOfHollowSpace^]
|https://opengeospatial.github.io/CityGML-3.0Encodings/xsd-doc/3.0/tunnel/#element_ADEOfTunnel[ADEOfTunnel^] |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfTunnel-section[ADEOfTunnel^]
|https://opengeospatial.github.io/CityGML-3.0Encodings/xsd-doc/3.0/tunnel/#element_ADEOfTunnelConstructiveElement[ADEOfTunnelConstructiveElement^] |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfTunnelConstructiveElement-section[ADEOfTunnelConstructiveElement^]
|https://opengeospatial.github.io/CityGML-3.0Encodings/xsd-doc/3.0/tunnel/#element_ADEOfTunnelFurniture[ADEOfTunnelFurniture^] |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfTunnelFurniture-section[ADEOfTunnelFurniture^]
|https://opengeospatial.github.io/CityGML-3.0Encodings/xsd-doc/3.0/tunnel/#element_ADEOfTunnelInstallation[ADEOfTunnelInstallation^] |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfTunnelInstallation-section[ADEOfTunnelInstallation^]
|https://opengeospatial.github.io/CityGML-3.0Encodings/xsd-doc/3.0/tunnel/#element_ADEOfTunnelPart[ADEOfTunnelPart^] |«DataType» https://docs.ogc.org/is/20-010/20-010.html#ADEOfTunnelPart-section[ADEOfTunnelPart^]
|===

Surface boundaries are constrained by the following requirement:

include::requirements/Tunnel/REQ_Tunnel_Boundaries.adoc[]

<<tunnel-boundaries-table>> lists the surfaces that are allowed as thematic surface boundaries of the space elements defined in the Tunnel module:

[[tunnel-boundaries-table]]
.Tunnel space elements and their allowed thematic surface boundaries
[cols="40,60",options="headers"]
|===
^|*Space element* ^|*Allowed space boundaries*
|_tun:AbstractTunnel_
a| * _con:AbstractConstructionSurface_ and the substitutable elements: +
{nbsp}{nbsp}{nbsp}{nbsp} _con:GroundSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:RoofSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:CeilingSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:OuterCeilingSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:FloorSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:OuterFloorSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:WallSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:InteriorWallSurface_
   * _core:ClosureSurface_
   * _gen:GenericThematicSurface_
   * possible surface elements from ADEs

|_tun:HollowSpace_
a| * _con:AbstractConstructionSurface_ and the substitutable elements: +
{nbsp}{nbsp}{nbsp}{nbsp} _con:GroundSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:RoofSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:CeilingSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:OuterCeilingSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:FloorSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:OuterFloorSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:WallSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:InteriorWallSurface_
   * _core:ClosureSurface_
   * _gen:GenericThematicSurface_
   * possible surface elements from ADEs

|_tun:Tunnel_
a| * _con:AbstractConstructionSurface_ and the substitutable elements: +
{nbsp}{nbsp}{nbsp}{nbsp} _con:GroundSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:RoofSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:CeilingSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:OuterCeilingSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:FloorSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:OuterFloorSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:WallSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:InteriorWallSurface_
   * _core:ClosureSurface_
   * _gen:GenericThematicSurface_
   * possible surface elements from ADEs

|_tun:TunnelConstructiveElement_
a| * _con:AbstractConstructionSurface_ and the substitutable elements: +
{nbsp}{nbsp}{nbsp}{nbsp} _con:GroundSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:RoofSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:CeilingSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:OuterCeilingSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:FloorSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:OuterFloorSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:WallSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:InteriorWallSurface_
   * _core:ClosureSurface_
   * _gen:GenericThematicSurface_
   * possible surface elements from ADEs

|_tun:TunnelFurniture_
a|No boundaries allowed

|_tun:TunnelInstallation_
a| * _con:AbstractConstructionSurface_ and the substitutable elements: +
{nbsp}{nbsp}{nbsp}{nbsp} _con:GroundSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:RoofSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:CeilingSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:OuterCeilingSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:FloorSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:OuterFloorSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:WallSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:InteriorWallSurface_
   * _core:ClosureSurface_
   * _gen:GenericThematicSurface_
   * possible surface elements from ADEs

|_tun:TunnelPart_
a| * _con:AbstractConstructionSurface_ and the substitutable elements: +
{nbsp}{nbsp}{nbsp}{nbsp} _con:GroundSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:RoofSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:CeilingSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:OuterCeilingSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:FloorSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:OuterFloorSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:WallSurface_, +
{nbsp}{nbsp}{nbsp}{nbsp} _con:InteriorWallSurface_
   * _core:ClosureSurface_
   * _gen:GenericThematicSurface_
   * possible surface elements from ADEs
|===
