[[scope-section]]

== Scope
This Standard documents the OGC GML <<implementation-specification-definition,Implementation Specification>> (IS) for the CityGML 3.0 Conceptual Model. The CityGML 3.0 conceptual model is a <<pim-definition,Platform Independent Model>> (PIM). It defines concepts in a manner which is independent of any implementing technology. As such, the CityGML Conceptual Model cannot be implemented directly. Rather, it serves as the base for <<psm-definition,Platform Specific Models>> (PSM). A PSM adds to the PIM the technology-specific details needed to fully define the CityGML model for use with a specific technology. The PSM can then be used to generate the schema and other artifacts needed to build CityGML 3.0 implementations.

This standard defines the PSMs and schemas for the CityGML 3.0 <<implementation-specification-definition,Implementation Specification>> (IS) for Geography Markup Language (GML) implemenations. The GML schemas are explained in an overview and design decisions that have been made are documented as well.
